### ISSUE TITLE
Status of CTrilinos/ForTrilinos?

### ISSUE THREAD

**Issue by dalg24** [trilinos/ForTrilinos#1]
I tried to symlink these two repos into my trilinos/packages directory and added the ``-D Trilinos_ENABLE_CTrilinos=ON`` and ``-D Trilinos_ENABLE_ForTrilinos=ON`` to my configure script but the variables were not used by cmake.
Where can I find instructions on how to build these two packages?

**Comment by bartlettroscoe** [comment]
If you clone CTrilinos and ForTrilinos under Trilinos/packages/ they should be picked up automatically (but I have not personally tested this).  The Trilinos-specific documentation has not been written yet but will be soon.  See trilinos/Trilinos#176.

But I don't think that we can add CTrilinos and ForTrilinos back to automated testing until we have done some testing that they still work.  I don't have access to a Fortran compiler that will build ForTrilinos so I can't safely add support for it (or it will just show up in automated Trilinos testing and could be broken).

I see two different options:

1) I add CTrilinos and ForTrilinos to Trilinos/cmake/ExtraRepositoriesList.cmake on a branch and then you can pull that branch and then run `./clone_extra_repos.py` to get these cloned the right place.  I can test that Trilinos picks them up correctly.

2) I add CTrilinos and ForTrilinos to Trilinos/cmake/ExtraRepositoriesList.cmake but change these to EX packages in Trilinos/PackagesList.cmake so that they get cloned but don't get picked up in automated Testing.

@bmpersc, and @jwillenbring, what do you think?

**Comment by bartlettroscoe** [comment]
@dalg24, I saw that ForTrilinos was already marked EX so it was safe to just add it to the ExtraRepositoriesList.cmake file.  I tested CTrilinos with the checkin-test.py script and it passed (so it should be okay in automated testing).

I will provide more documentation later, but you can get these by simply doing:

```
$ git clone git@github.com:trilinos/Trilinos
$ cd Trilinos/
$ ./clone_extra_repos.py
```

Once you do that, you should be able to just configure Trilinos:

```
-D Trilinos_ENABLE_CTrilinos=ON -D Trilinos_ENABLE_ForTrilinos=ON
```

and they should get enabled.

If that does not work, please let me know by re-opening this Issue.

**Comment by dalg24** [comment]
@bartlettroscoe: It worked. Thank you.
