### ISSUE TITLE
Decide on unit test framework

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#16]
Variants so far:

1. @sethrj started with DBCF
2. ForTrilinos v1 has unit test framework that reminds general Trilinos.

I'm leaning towards picking up pieces of v1 framework

**Comment by rouson** [comment]
For unit testing modern Fortran, I recommend evaluating [pFUnit] developed by Tom Clune of NASA Goddard Space Flight Center.

[pFUnit]: http://pfunit.sourceforge.net

**Comment by aprokop** [comment]
@rouson Do you know if/how well it integrates with CTest?

**Comment by rouson** [comment]
The pFUnit build scripts are written in CMake, but I don't believe pFUnit once built interacts with CMake in any way.  The leader of the pFUnit project is very responsive so I'd recommend contacting him. I'll try tagging him in this comment in case that works: @tclune.

**Comment by youngmit** [comment]
We have a lighter-weight module and set of macros that we use for MPACT testing that we could use. It doesn't require preprocessing files, just include a header, import a module and that's it.

**Comment by youngmit** [comment]
I should mention that this is in Futility, so it's open source unlike the lion's share of MPACT.

**Comment by tclune** [comment]
The preprocessing for pFUnit tests is not essential - it merely alleviates some of the common boiler plate code that otherwise arises.   E.g., automatically register the tests with the framework,  check if _any_ process raised an exception on an assertion, include the file name and line number in the failure message, etc.

Things like:

@mpiAssertEqual(x,y)

expand to something like :

call assertEqual(x, y, SourceLocation(__FILE__,__LINE__))
if (anyExceptions()) return

Cheers,

- Tom





On Mar 14, 2017, at 9:36 AM, Mitchell T.H. Young <notifications@github.com<mailto:notifications@github.com>> wrote:


We have a lighter-weight module and set of macros that we use for MPACT testing that we could use. It doesn't require preprocessing files, just include a header, import a module and that's it.

**Comment by aprokop** [comment]
One concern that I have even without carefully through the actual package (which looks quite nice at a glance) is that it is under "NASA Open Source Agreement" license which OSI considers open source while FSF does not. I'm not a lawyer so I'm not sure how it will interact with a BSD license.

**Comment by aprokop** [comment]
@tjfulle implemented a set of macros that are suitable for unit testing (see `FortranTestMacros.h` for the macros definitions, and `test_tpetra_map.f90` for usage examples).
